apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-keycloak
resources:
  - namespace.yaml
  - secret.yaml
  - pvc-postgresql.yaml
  - deployment-postgresql.yaml
  - service-postgresql.yaml
  - deployment-keycloak.yaml
  - service-keycloak.yaml
  - route-keycloak.yaml
images:
  - name: demo-keycloak-image
    newName: registry.cluster.lan/apps/keycloak/keycloak
    newTag: "26.5"
  - name: demo-postgres-image
    newName: registry.cluster.lan/apps/library/postgresql
    newTag: "18.1"
