apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Stephan-Reinhardt/gitops-test.git
    targetRevision: main
    path: apps/hello
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true