apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/namespaces
#  - ../../components/operators
#  - ../../components/ldap
#  - ../../components/hardening
#  - ../../components/local-storage
#  - localvolumeset.yaml
#patches:
#  - path: ldap-patch.yaml