apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-ca-bundle
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_LDAP_CA
    -----END CERTIFICATE-----
